language: csharp
solution: LastLetter.sln
mono: none
dotnet: 3.0.100
sudo: false
after_success: coveralls
branches:
  only:
  - master
  - develop
script:
  - dotnet restore
  - dotnet build
  - dotnet test ./tests/Game.UnitTests -c Release -f netcoreapp3.0
